export const USER_STATUSES = {
   ACTIVE: 'ACTIVE', 
   BANNED: 'BANNED',
};

export const USER_ROLES = {
   CUSTOMER: 'CUSTOMER',
   MANAGER: 'MANAGER',
   ADMIN: 'ADMIN',
}

export const DELIVERY_STATUSES = {
   IN_TRANSIT: 'IN_TRANSIT', 
   DELIVERED: 'DELIVERED', 
   RECEIVED: 'RECIEVED',
};

export const AUTHORIZATION_ACCESS_SECRET_KEY = process.env.ACCESS_SECRET_KEY;
export const AUTHORIZATION_REFRESH_SECRET_KEY = process.env.REFRESH_SECRET_KEY;