export const USER_STATUSES = {
   ACTIVE: 'ACTIVE', 
   BANNED: 'BANNED',
};

export const USER_ROLES = {
   CUSTOMER: 'CUSTOMER',
   MANAGER: 'MANAGER',
   ADMIN: 'ADMIN',
}

export const DELIVERY_STATUSES = {
   IN_TRANSIT: 'IN_TRANSIT', 
   DELIVERED: 'DELIVERED', 
   RECEIVED: 'RECIEVED',
};

export const COMMENT_TYPES = {
   REVIEW: 'REVIEW',
   COMMENT: 'COMMENT',
}

export const REACTIONS_TO_COMMENT = {
   LIKE: 'LIKE',
   DISLIKE: 'DISLIKE',
}

export const AUTHORIZATION_ACCESS_SECRET_KEY = process.env.ACCESS_SECRET_KEY;
export const AUTHORIZATION_REFRESH_SECRET_KEY = process.env.REFRESH_SECRET_KEY;

export const THROW_ERROR_MESSAGES = {
   FORBIDDEN: 'FORBIDDEN',
   NO_ACCESS_RIGHTS: 'NO ACCESS RIGHTS',
   USER_NOT_FOUND: 'USER NOT FOUND',
   ORDER_NOT_FOUND: 'ORDER NOT FOUND',
   PRODUCT_NOT_FOUND: 'PRODUCT NOT FOUND',
   CATEGORY_NOT_FOUND: 'CATEGORY NOT FOUND',
   COMMENT_NOT_FOUND: 'COMMENT NOT FOUND',
   USER_ALREADY_EXISTS: 'USER ALREADY EXISTS',
   PRODUCT_ALREADY_EXISTS: 'PRODUCT ALREADY EXISTS',
   CATEGORY_ALREADY_EXISTS: 'CATEGORY ALREADY EXISTS',
   PAYMENT_PROHIBITED: 'PAYMENT PROHIBITED',
}